version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: MySql_Con
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FBA_DATABASE
      MYSQL_USER: shivam
      MYSQL_PASSWORD: Shibam#1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
