DELETE FROM ROLES WHERE ID = 1 AND NAME ='ADMIN';
INSERT INTO ROLES (NAME,ID,CREATED_AT,UPDATED_AT) VALUES ('ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

DELETE FROM ROLES WHERE ID = 2 AND NAME ='USER';
INSERT INTO ROLES (NAME,ID,CREATED_AT,UPDATED_AT) VALUES ('USER',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
